# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tiulo',
            new_name='titulo',
        ),
    ]
